globalThis.localStorage = (() => { let s={}; return {getItem:k=>k in s?s[k]:null,setItem:(k,v)=>{s[k]=String(v)},removeItem:k=>{delete s[k]},clear:()=>{s={}}} })();
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
const { default: Contacts } = await import("./src/modules/SHOS_Contacts_Prototype.jsx");
const { default: Encounters } = await import("./src/modules/SHOS_Encounters_Prototype.jsx");
const { default: Testing } = await import("./src/modules/SHOS_Testing_Prototype.jsx");
const { default: ClinicVisits } = await import("./src/modules/SHOS_ClinicVisits_Prototype.jsx");
console.log("Contacts:", renderToStaticMarkup(React.createElement(Contacts)).length, "chars");
console.log("Encounters:", renderToStaticMarkup(React.createElement(Encounters)).length, "chars");
console.log("Testing:", renderToStaticMarkup(React.createElement(Testing)).length, "chars");
console.log("ClinicVisits:", renderToStaticMarkup(React.createElement(ClinicVisits)).length, "chars");
